COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= auto_low_power.c

API_LOCATION ?= ../..

COMMON_LOCATION ?= ..

C_SRCS += \
$(API_LOCATION)/bma4.c \
$(API_LOCATION)/bma456mm.c \
$(COMMON_LOCATION)/common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
$(COMMON_LOCATION)/common

include $(COINES_INSTALL_PATH)/coines.mk